status = [
  "Lint",
  "repos REPO:https://github.com/duckinator/bork.git",
  "repos REPO:https://github.com/duckinator/emanate.git",
  "repos REPO:https://github.com/ppb/ppb-vector.git",
  "repos REPO:https://github.com/astronouth7303/ppb-mutant.git",
]
